apiVersion: v1
kind: Service
metadata:
  name: xiao-yang-svc
  namespace: xiao-yang
spec:
  selector:
    app: xiao-yang
  type: ClusterIP
  ports:
    - name: xiao-yang-svc-http-port
      port: 8080
      targetPort: 8080

