apiVersion: apps/v1
kind: Deployment
metadata:
  name: xiao-yang-dm
  namespace: xiao-yang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xiao-yang
  template:
    metadata:
      name: xiao-yang-pod
      labels:
        app: xiao-yang
    spec:
      containers:
        - name: xiao-yang
          image: /xiao-yang/xiao-yang:latest
          # If using a local image, use Never, default is Always
          #imagePullPolicy: Never
          command: ["./XiaoYang", "-c", "/app/configs/XiaoYang.yml"]
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          volumeMounts:
            - name: xiao-yang-vl
              mountPath: /app/configs/
              readOnly: true

          ports:
            - name: http-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              port: http-port
              path: /health
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: http-port
              path: /health

            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      # todo for private repositories, you need to create a secret (here docker-auth-secret) to store the account and password to log into docker
      imagePullSecrets:
        - name: docker-auth-secret
      volumes:
        - name: xiao-yang-vl
          configMap:
            name: xiao-yang-config
