kind: ConfigMap
apiVersion: v1
metadata:
  name: xiao-yang-config
  namespace: xiao-yang
data:
  XiaoYang.yml: |-
    # If you need to convert YAML to a Go struct, please execute the command: make update-config
    
    # app settings
    app:
      name: "XiaoYang"      # server name
      env: "dev"                     # runtime environment, dev: development environment, prod: production environment, test: test environment
      version: "v0.0.0"
      host: "127.0.0.1"              # domain or ip, for service registration
      enableStat: true               # whether to turn on printing statistics, true:enable, false:disable
      enableMetrics: true            # whether to turn on indicator collection, true:enable, false:disable
      enableHTTPProfile: false       # whether to turn on performance analysis, true:enable, false:disable
      enableLimit: false             # whether to turn on rate limiting (adaptive), true:on, false:off
      enableCircuitBreaker: false    # whether to turn on circuit breaker(adaptive), true:on, false:off
      enableTrace: false             # whether to turn on trace, true:enable, false:disable, if true jaeger configuration must be set
      tracingSamplingRate: 1.0       # tracing sampling rate, between 0 and 1, 0 means no sampling, 1 means sampling all links
      #registryDiscoveryType: ""      # registry and discovery types: consul, etcd, nacos, if empty, registration and discovery are not used
      cacheType: ""                  # cache type, if empty, the cache is not used, support for "memory" and "redis", if set to redis, must set redis configuration
    
    
    # http server settings
    http:
      port: 8080                # listen port
      timeout: 0                # request timeout, unit(second), if 0 means not set, if greater than 0 means set timeout, if enableHTTPProfile is true, it needs to set 0 or greater than 60s
    
    
    
    # logger settings
    logger:
      level: "info"             # output log levels debug, info, warn, error, default is debug
      format: "console"         # output format, console or json, default is console
      isSave: false             # false:output to terminal, true:output to file, default is false
      #logFileConfig:           # Effective when isSave=true
        #filename: "out.log"    # File name (default is out.log)
        #maxSize: 20            # Maximum file size (MB, default is 10MB)
        #maxBackups: 50         # Maximum number of old files to retain (default is 100)
        #maxAge: 15             # Maximum number of days to retain old files (default is 30 days)
        #isCompression: true    # Whether to compress/archive old files (default is false)
    
    
    # set database configuration. reference-db-config-url
    database:
      driver: "mysql"           # database driver
      # mysql settings
      mysql:
        # dsn format,  <username>:<password>@(<hostname>:<port>)/<db>?[k=v& ......]
        dsn: "root:123456@(192.168.3.37:3306)/account?parseTime=true&loc=Local&charset=utf8,utf8mb4"
        enableLog: true         # whether to turn on printing of all logs
        maxIdleConns: 10        # set the maximum number of connections in the idle connection pool
        maxOpenConns: 100       # set the maximum number of open database connections
        connMaxLifetime: 30     # sets the maximum time for which the connection can be reused, in minutes
    
    
    
    # redis settings
    redis:
      # dsn format, [user]:<pass>@127.0.0.1:6379/[db], the default user is default, redis version 6.0 and above only supports user.
      dsn: "default:123456@192.168.3.37:6379/0"
      dialTimeout: 10           # connection timeout, unit(second)
      readTimeout: 2            # read timeout, unit(second)
      writeTimeout: 2           # write timeout, unit(second)
    
    
    # jaeger settings
    jaeger:
      agentHost: "192.168.3.37"
      agentPort: 6831
    
    
    
    
