version: '3.3'
services:
  client:
    image: docker.io/66maer/zyhm-client:latest
    ports:
      - "80:80"

  server:
    image: docker.io/66maer/zyhm-server:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env.prod

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db

volumes:
  db_data:
