version: '3.8'
services:
  server:
    build:
      context: ./server
    ports:
      - "45361:5000"
    depends_on:
      - mongo
    env_file:
      - .env.local
    volumes:
      - ./server:/app
      - /app/node_modules

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db

volumes:
  db_data:
