version: '3.3'
services:
  # client:
  #   image: docker.io/66maer/zyhm-client:latest
  #   ports:
  #     - "80:80"

  # server:
  #   image: docker.io/66maer/zyhm-server:latest
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - psql_db
  #   env_file:
  #     - .env.prod

  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./db_data:/data/db

  psql_db:
    image: postgres:16.3
    container_name: psql_db
    env_file:
      - .env.prod
    volumes:
      - ./psql_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    