version: '3.3'
services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env.prod
    volumes:
      - ./server:/app
      - /app/node_modules

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db

volumes:
  db_data:
