// Code generated by https://github.com/go-dev-frame/sponge

package routers

import (
	"github.com/gin-gonic/gin"

	"github.com/go-dev-frame/sponge/pkg/logger"
	//"github.com/go-dev-frame/sponge/pkg/middleware"

	XiaoYangV1 "XiaoYang/api/XiaoYang/v1"
	"XiaoYang/internal/handler"
)

func init() {
	allMiddlewareFns = append(allMiddlewareFns, func(c *middlewareConfig) {
		teamServiceMiddlewares(c)
	})

	allRouteFns = append(allRouteFns,
		func(r *gin.Engine, groupPathMiddlewares map[string][]gin.HandlerFunc, singlePathMiddlewares map[string][]gin.HandlerFunc) {
			teamServiceRouter(r, groupPathMiddlewares, singlePathMiddlewares, handler.NewTeamServiceHandler())
		})
}

func teamServiceRouter(
	r *gin.Engine,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iService XiaoYangV1.TeamServiceLogicer) {
	XiaoYangV1.RegisterTeamServiceRouter(
		r,
		groupPathMiddlewares,
		singlePathMiddlewares,
		iService,
		XiaoYangV1.WithTeamServiceLogger(logger.Get()),
		XiaoYangV1.WithTeamServiceHTTPResponse(),
		XiaoYangV1.WithTeamServiceErrorToHTTPCode(
		// Set some error codes to standard http return codes,
		// by default there is already ecode.InternalServerError and ecode.ServiceUnavailable
		// example:
		// 	ecode.Forbidden, ecode.LimitExceed,
		),
	)
}

// you can set the middleware of a route group, or set the middleware of a single route,
// or you can mix them, pay attention to the duplication of middleware when mixing them,
// it is recommended to set the middleware of a single route in preference
func teamServiceMiddlewares(c *middlewareConfig) {
	// set up group route middleware, group path is left prefix rules,
	// if the left prefix is hit, the middleware will take effect, e.g. group route is /api/v1, route /api/v1/teamService/:id  will take effect
	// c.setGroupPath("/api/v1/teamService", middleware.Auth())

	// set up single route middleware, just uncomment the code and fill in the middlewares, nothing else needs to be changed
	//c.setSinglePath("POST", "/api/v1/team/createTeam", middleware.Auth())    // CreateTeam 开团
	//c.setSinglePath("POST", "/api/v1/team/closeTeam", middleware.Auth())    // CloseTeam 关闭团队
	//c.setSinglePath("POST", "/api/v1/team/updateTeam", middleware.Auth())    // UpdateTeam 修改开团信息
	//c.setSinglePath("POST", "/api/v1/template/createTemplate", middleware.Auth())    // CreateTemplate 新增模板
	//c.setSinglePath("POST", "/api/v1/template/deleteTemplate", middleware.Auth())    // DeleteTemplate 删除模板
	//c.setSinglePath("POST", "/api/v1/template/updateTemplate", middleware.Auth())    // UpdateTemplate 修改模板
	//c.setSinglePath("POST", "/api/v1/team/getTeam", middleware.Auth())    // GetTeam 获取开团信息
	//c.setSinglePath("POST", "/api/v1/team/listTeams", middleware.Auth())    // ListTeams 获取所有开团信息
	//c.setSinglePath("POST", "/api/v1/template/getTemplate", middleware.Auth())    // GetTemplate 获取模板信息
	//c.setSinglePath("POST", "/api/v1/template/listTemplates", middleware.Auth())    // ListTemplates 获取所有模板信息
}
