// Code generated by https://github.com/go-dev-frame/sponge

package ecode

import (
	"github.com/go-dev-frame/sponge/pkg/errcode"
)

// characterService business-level http error codes.
// the characterServiceNO value range is 1~100, if the same error code is used, it will cause panic.
var (
	characterServiceNO       = 45
	characterServiceName     = "characterService"
	characterServiceBaseCode = errcode.HCode(characterServiceNO)

	ErrCreateCharacterCharacterService    = errcode.NewError(characterServiceBaseCode+1, "failed to CreateCharacter "+characterServiceName)
	ErrUpdateCharacterCharacterService    = errcode.NewError(characterServiceBaseCode+2, "failed to UpdateCharacter "+characterServiceName)
	ErrDeleteCharacterCharacterService    = errcode.NewError(characterServiceBaseCode+3, "failed to DeleteCharacter "+characterServiceName)
	ErrGetCharacterCharacterService       = errcode.NewError(characterServiceBaseCode+4, "failed to GetCharacter "+characterServiceName)
	ErrListUserCharactersCharacterService = errcode.NewError(characterServiceBaseCode+5, "failed to ListUserCharacters "+characterServiceName)

	// error codes are globally unique, adding 1 to the previous error code
)
