// Code generated by https://github.com/go-dev-frame/sponge

package ecode

import (
	"github.com/go-dev-frame/sponge/pkg/errcode"
)

// signupService business-level http error codes.
// the signupServiceNO value range is 1~100, if the same error code is used, it will cause panic.
var (
	signupServiceNO       = 46
	signupServiceName     = "signupService"
	signupServiceBaseCode = errcode.HCode(signupServiceNO)

	ErrCreateSignupSignupService     = errcode.NewError(signupServiceBaseCode+1, "failed to CreateSignup "+signupServiceName)
	ErrCancelSignupSignupService     = errcode.NewError(signupServiceBaseCode+2, "failed to CancelSignup "+signupServiceName)
	ErrGetSignupsByTeamSignupService = errcode.NewError(signupServiceBaseCode+3, "failed to GetSignupsByTeam "+signupServiceName)

	// error codes are globally unique, adding 1 to the previous error code
)
