// Code generated by https://github.com/zhufuyi/sponge

package routers

import (
	"github.com/gin-gonic/gin"

	"github.com/zhufuyi/sponge/pkg/logger"
	//"github.com/zhufuyi/sponge/pkg/middleware"

	xiaoyangV1 "xiaoyang/api/xiaoyang/v1"
	"xiaoyang/internal/handler"
)

func init() {
	allMiddlewareFns = append(allMiddlewareFns, func(c *middlewareConfig) {
		teamServiceMiddlewares(c)
	})

	allRouteFns = append(allRouteFns,
		func(r *gin.Engine, groupPathMiddlewares map[string][]gin.HandlerFunc, singlePathMiddlewares map[string][]gin.HandlerFunc) {
			teamServiceRouter(r, groupPathMiddlewares, singlePathMiddlewares, handler.NewTeamServiceHandler())
		})
}

func teamServiceRouter(
	r *gin.Engine,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iService xiaoyangV1.TeamServiceLogicer) {
	xiaoyangV1.RegisterTeamServiceRouter(
		r,
		groupPathMiddlewares,
		singlePathMiddlewares,
		iService,
		xiaoyangV1.WithTeamServiceLogger(logger.Get()),
		xiaoyangV1.WithTeamServiceHTTPResponse(),
		xiaoyangV1.WithTeamServiceErrorToHTTPCode(
		// Set some error codes to standard http return codes,
		// by default there is already ecode.InternalServerError and ecode.ServiceUnavailable
		// example:
		// 	ecode.Forbidden, ecode.LimitExceed,
		),
	)
}

// you can set the middleware of a route group, or set the middleware of a single route,
// or you can mix them, pay attention to the duplication of middleware when mixing them,
// it is recommended to set the middleware of a single route in preference
func teamServiceMiddlewares(c *middlewareConfig) {
	// set up group route middleware, group path is left prefix rules,
	// if the left prefix is hit, the middleware will take effect, e.g. group route is /api/v1, route /api/v1/teamService/:id  will take effect
	// c.setGroupPath("/api/v1/teamService", middleware.Auth())

	// set up single route middleware, just uncomment the code and fill in the middlewares, nothing else needs to be changed
	//c.setSinglePath("POST", "/v1/team", middleware.Auth())
	//c.setSinglePath("GET", "/v1/team/list", middleware.Auth())
	//c.setSinglePath("GET", "/v1/team/active", middleware.Auth())
	//c.setSinglePath("PUT", "/v1/team", middleware.Auth())
	//c.setSinglePath("POST", "/v1/team/visible", middleware.Auth())
	//c.setSinglePath("POST", "/v1/team/lock", middleware.Auth())
	//c.setSinglePath("POST", "/v1/team/close", middleware.Auth())
	//c.setSinglePath("POST", "/v1/team_template", middleware.Auth())
	//c.setSinglePath("GET", "/v1/team_template/list", middleware.Auth())
	//c.setSinglePath("DELETE", "/v1/team_template", middleware.Auth())
}
