// Code generated by https://github.com/zhufuyi/sponge

package routers

import (
	"github.com/gin-gonic/gin"

	"github.com/zhufuyi/sponge/pkg/logger"
	//"github.com/zhufuyi/sponge/pkg/middleware"

	xiaoyangV1 "xiaoyang/api/xiaoyang/v1"
	"xiaoyang/internal/handler"
)

func init() {
	allMiddlewareFns = append(allMiddlewareFns, func(c *middlewareConfig) {
		userServiceMiddlewares(c)
	})

	allRouteFns = append(allRouteFns,
		func(r *gin.Engine, groupPathMiddlewares map[string][]gin.HandlerFunc, singlePathMiddlewares map[string][]gin.HandlerFunc) {
			userServiceRouter(r, groupPathMiddlewares, singlePathMiddlewares, handler.NewUserServiceHandler())
		})
}

func userServiceRouter(
	r *gin.Engine,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iService xiaoyangV1.UserServiceLogicer) {
	xiaoyangV1.RegisterUserServiceRouter(
		r,
		groupPathMiddlewares,
		singlePathMiddlewares,
		iService,
		xiaoyangV1.WithUserServiceLogger(logger.Get()),
		xiaoyangV1.WithUserServiceHTTPResponse(),
		xiaoyangV1.WithUserServiceErrorToHTTPCode(
		// Set some error codes to standard http return codes,
		// by default there is already ecode.InternalServerError and ecode.ServiceUnavailable
		// example:
		// 	ecode.Forbidden, ecode.LimitExceed,
		),
	)
}

// you can set the middleware of a route group, or set the middleware of a single route,
// or you can mix them, pay attention to the duplication of middleware when mixing them,
// it is recommended to set the middleware of a single route in preference
func userServiceMiddlewares(c *middlewareConfig) {
	// set up group route middleware, group path is left prefix rules,
	// if the left prefix is hit, the middleware will take effect, e.g. group route is /api/v1, route /api/v1/userService/:id  will take effect
	// c.setGroupPath("/api/v1/userService", middleware.Auth())

	// set up single route middleware, just uncomment the code and fill in the middlewares, nothing else needs to be changed
	//c.setSinglePath("POST", "/v1/auth/register", middleware.Auth())
	//c.setSinglePath("POST", "/v1/auth/login", middleware.Auth())
	//c.setSinglePath("POST", "/v1/auth/logout", middleware.Auth())
	//c.setSinglePath("GET", "/v1/user/:qq_number", middleware.Auth())
	//c.setSinglePath("PUT", "/v1/user/:qq_number", middleware.Auth())
	//c.setSinglePath("PUT", "/v1/user/password/:qq_number", middleware.Auth())
}
