// Code generated by https://github.com/zhufuyi/sponge

package handler

import (
	"context"

	//"github.com/zhufuyi/sponge/pkg/gin/middleware"

	XiaoYangV1 "XiaoYang/api/XiaoYang/v1"
	"XiaoYang/internal/cache"
	"XiaoYang/internal/dao"
	"XiaoYang/internal/database"
)

var _ XiaoYangV1.UserServiceLogicer = (*userServiceHandler)(nil)

type userServiceHandler struct {
	userDao dao.UsersDao
}

// NewUserServiceHandler create a handler
func NewUserServiceHandler() XiaoYangV1.UserServiceLogicer {
	return &userServiceHandler{
		userDao: dao.NewUsersDao(
			database.GetDB(),
			cache.NewUsersCache(database.GetCacheType()),
		),
	}
}

// Register 注册
func (h *userServiceHandler) Register(ctx context.Context, req *XiaoYangV1.RegisterRequest) (*XiaoYangV1.RegisterResponse, error) {
	panic("implement me")

	// fill in the business logic code here
	// example:
	//
	//	    err := req.Validate()
	//	    if err != nil {
	//		    logger.Warn("req.Validate error", logger.Err(err), logger.Any("req", req), middleware.CtxRequestIDField(ctx))
	//		    return nil, ecode.InvalidParams.Err()
	//	    }
	//
	//	    reply, err := h.userServiceDao.Register(ctx, &model.UserService{
	//     	QqNumber: req.QqNumber,
	//     	Password: req.Password,
	//     	Nickname: req.Nickname,
	//     })
	//	    if err != nil {
	//			logger.Warn("Register error", logger.Err(err), middleware.CtxRequestIDField(ctx))
	//			return nil, ecode.InternalServerError.Err()
	//		}
	//
	//     return &XiaoYangV1.RegisterResponse{
	//     	Token: reply.Token,
	//     	UserId: reply.UserId,
	//     	QqNumber: reply.QqNumber,
	//     	Nickname: reply.Nickname,
	//     	Avatar: reply.Avatar,
	//     }, nil
}

// Login 登录
func (h *userServiceHandler) Login(ctx context.Context, req *XiaoYangV1.LoginRequest) (*XiaoYangV1.LoginResponse, error) {
	panic("implement me")

	// fill in the business logic code here
	// example:
	//
	//	    err := req.Validate()
	//	    if err != nil {
	//		    logger.Warn("req.Validate error", logger.Err(err), logger.Any("req", req), middleware.CtxRequestIDField(ctx))
	//		    return nil, ecode.InvalidParams.Err()
	//	    }
	//
	//	    reply, err := h.userServiceDao.Login(ctx, &model.UserService{
	//     	QqNumber: req.QqNumber,
	//     	Password: req.Password,
	//     })
	//	    if err != nil {
	//			logger.Warn("Login error", logger.Err(err), middleware.CtxRequestIDField(ctx))
	//			return nil, ecode.InternalServerError.Err()
	//		}
	//
	//     return &XiaoYangV1.LoginResponse{
	//     	Token: reply.Token,
	//     	UserId: reply.UserId,
	//     	QqNumber: reply.QqNumber,
	//     	Nickname: reply.Nickname,
	//     	Avatar: reply.Avatar,
	//     }, nil
}

// Logout 登出
func (h *userServiceHandler) Logout(ctx context.Context, req *XiaoYangV1.LogoutRequest) (*XiaoYangV1.LogoutResponse, error) {
	panic("implement me")

	// fill in the business logic code here
	// example:
	//
	//	    err := req.Validate()
	//	    if err != nil {
	//		    logger.Warn("req.Validate error", logger.Err(err), logger.Any("req", req), middleware.CtxRequestIDField(ctx))
	//		    return nil, ecode.InvalidParams.Err()
	//	    }
	//
	//	    reply, err := h.userServiceDao.Logout(ctx, &model.UserService{
	//     	UserId: req.UserId,
	//     })
	//	    if err != nil {
	//			logger.Warn("Logout error", logger.Err(err), middleware.CtxRequestIDField(ctx))
	//			return nil, ecode.InternalServerError.Err()
	//		}
	//
	//     return &XiaoYangV1.LogoutResponse{
	//     }, nil
}

// GetUserInfo 获取用户信息
func (h *userServiceHandler) GetUserInfo(ctx context.Context, req *XiaoYangV1.GetUserInfoRequest) (*XiaoYangV1.GetUserInfoResponse, error) {
	panic("implement me")

	// fill in the business logic code here
	// example:
	//
	//	    err := req.Validate()
	//	    if err != nil {
	//		    logger.Warn("req.Validate error", logger.Err(err), logger.Any("req", req), middleware.CtxRequestIDField(ctx))
	//		    return nil, ecode.InvalidParams.Err()
	//	    }
	//
	//	    reply, err := h.userServiceDao.GetUserInfo(ctx, &model.UserService{
	//     	UserId: req.UserId,
	//     })
	//	    if err != nil {
	//			logger.Warn("GetUserInfo error", logger.Err(err), middleware.CtxRequestIDField(ctx))
	//			return nil, ecode.InternalServerError.Err()
	//		}
	//
	//     return &XiaoYangV1.GetUserInfoResponse{
	//     	UserId: reply.UserId,
	//     	QqNumber: reply.QqNumber,
	//     	Nickname: reply.Nickname,
	//     	Avatar: reply.Avatar,
	//     }, nil
}

// UpdateUserInfo 更新用户信息
func (h *userServiceHandler) UpdateUserInfo(ctx context.Context, req *XiaoYangV1.UpdateUserInfoRequest) (*XiaoYangV1.UpdateUserInfoResponse, error) {
	panic("implement me")

	// fill in the business logic code here
	// example:
	//
	//	    err := req.Validate()
	//	    if err != nil {
	//		    logger.Warn("req.Validate error", logger.Err(err), logger.Any("req", req), middleware.CtxRequestIDField(ctx))
	//		    return nil, ecode.InvalidParams.Err()
	//	    }
	//
	//	    reply, err := h.userServiceDao.UpdateUserInfo(ctx, &model.UserService{
	//     	UserId: req.UserId,
	//     	QqNumber: req.QqNumber,
	//     	Nickname: req.Nickname,
	//     	Avatar: req.Avatar,
	//     })
	//	    if err != nil {
	//			logger.Warn("UpdateUserInfo error", logger.Err(err), middleware.CtxRequestIDField(ctx))
	//			return nil, ecode.InternalServerError.Err()
	//		}
	//
	//     return &XiaoYangV1.UpdateUserInfoResponse{
	//     }, nil
}

// ChangePassword 修改密码
func (h *userServiceHandler) ChangePassword(ctx context.Context, req *XiaoYangV1.ChangePasswordRequest) (*XiaoYangV1.ChangePasswordResponse, error) {
	panic("implement me")

	// fill in the business logic code here
	// example:
	//
	//	    err := req.Validate()
	//	    if err != nil {
	//		    logger.Warn("req.Validate error", logger.Err(err), logger.Any("req", req), middleware.CtxRequestIDField(ctx))
	//		    return nil, ecode.InvalidParams.Err()
	//	    }
	//
	//	    reply, err := h.userServiceDao.ChangePassword(ctx, &model.UserService{
	//     	UserId: req.UserId,
	//     	QqNumber: req.QqNumber,
	//     	OldPassword: req.OldPassword,
	//     	NewPassword: req.NewPassword,
	//     })
	//	    if err != nil {
	//			logger.Warn("ChangePassword error", logger.Err(err), middleware.CtxRequestIDField(ctx))
	//			return nil, ecode.InternalServerError.Err()
	//		}
	//
	//     return &XiaoYangV1.ChangePasswordResponse{
	//     }, nil
}
