export const xinfaInfoTable = {
  huajian: {
    name: "花间游",
    nickname: ["花间", "花间游", "草里爬"],
    menpai: "万花",
    icon: "huajian.png",
    color: "#c498ff",
    type: ["dps", "内功", "元气"],
  },
  lijing: {
    name: "离经易道",
    nickname: ["奶花", "离经易道", "离经", "花奶"],
    menpai: "万花",
    icon: "lijing.png",
    color: "#c498ff",
    type: ["奶妈"],
  },
  binxin: {
    name: "冰心诀",
    nickname: ["冰心", "冰心诀", "冰心决"],
    menpai: "七秀",
    icon: "binxin.png",
    color: "#ff81b0",
    type: ["dps", "内功", "根骨"],
  },
  yunchang: {
    name: "云裳心经",
    nickname: ["奶秀", "云裳心经", "云裳", "秀奶"],
    menpai: "七秀",
    icon: "yunchang.png",
    color: "#ff81b0",
    type: ["奶妈"],
  },
  yijin: {
    name: "易筋经",
    nickname: ["和尚", "易筋经", "易筋", "秃子", "光头", "灯泡", "秃驴"],
    menpai: "少林",
    icon: "yijin.png",
    color: "#ffb25f",
    type: ["dps", "内功", "元气"],
  },
  xisui: {
    name: "洗髓经",
    nickname: ["和尚T", "洗髓经", "洗髓", "秃T", "圣僧", "佛祖"],
    menpai: "少林",
    icon: "xisui.png",
    color: "#ffb25f",
    type: ["T"],
  },
  zixia: {
    name: "紫霞功",
    nickname: ["气纯", "紫霞功", "紫霞"],
    menpai: "纯阳",
    icon: "zixia.png",
    color: "#16d8d8",
    type: ["dps", "内功", "根骨"],
  },
  taixu: {
    name: "太虚剑意",
    nickname: ["剑纯", "太虚剑意", "备胎"],
    menpai: "纯阳",
    icon: "taixu.png",
    color: "#16d8d8",
    type: ["dps", "外功", "身法"],
  },
  aoxue: {
    name: "傲血战意",
    nickname: ["天策", "傲血战意", "傲血", "傲雪", "哈士奇", "狗子", "二哈"],
    menpai: "天策",
    icon: "aoxue.png",
    color: "#ff6f53",
    type: ["dps", "外功", "力道"],
  },
  tielao: {
    name: "铁牢律",
    nickname: ["策T", "铁牢律", "铁牢", "天策T"],
    menpai: "天策",
    icon: "tielao.png",
    color: "#ff6f53",
    type: ["T"],
  },
  wenshui: {
    name: "问水诀",
    nickname: ["藏剑", "问水诀", "问水", "问水决", "黄鸡", "叽", "黄叽", "KFC", "kfc", "星期四"],
    menpai: "藏剑",
    icon: "wenshui.png",
    color: "#d6f95d",
    type: ["dps", "外功", "身法"],
  },
  // 山居和问水算一个
  dujing: {
    name: "毒经",
    nickname: ["毒经", "五毒"],
    menpai: "五毒",
    icon: "dujing.png",
    color: "#3793ff",
    type: ["dps", "内功", "根骨"],
  },
  butian: {
    name: "补天诀",
    nickname: ["奶毒", "补天诀", "补天", "毒奶"],
    menpai: "五毒",
    icon: "butian.png",
    color: "#3793ff",
    type: ["奶妈"],
  },
  jingyu: {
    name: "惊羽诀",
    nickname: ["鲸鱼", "惊羽诀", "惊羽", "惊羽决"],
    menpai: "唐门",
    icon: "jingyu.png",
    color: "#79b736",
    type: ["dps", "外功", "力道"],
  },
  tianluo: {
    name: "天罗诡道",
    nickname: ["田螺", "天罗诡道", "天罗"],
    menpai: "唐门",
    icon: "tianluo.png",
    color: "#79b736",
    type: ["dps", "内功", "元气"],
  },
  fenying: {
    name: "焚影圣诀",
    nickname: ["焚影", "焚影圣诀", "喵", "喵喵", "明教"],
    menpai: "明教",
    icon: "fenying.png",
    color: "#f04660",
    type: ["dps", "内功", "元气"],
  },
  mingzun: {
    name: "明尊琉璃体",
    nickname: ["喵T", "明尊琉璃体", "明尊", "明教T"],
    menpai: "明教",
    icon: "mingzun.png",
    color: "#f04660",
    type: ["T"],
  },
  xiaochen: {
    name: "笑尘诀",
    nickname: ["丐帮", "笑尘诀", "帅比", "无敌心法", "最强心法"],
    menpai: "丐帮",
    icon: "xiaochen.png",
    color: "#cd853f",
    type: ["dps", "外功", "力道"],
  },
  fenshan: {
    name: "分山劲",
    nickname: ["苍云", "分山劲", "分山", "岔劲", "乌龟", "龟龟", "盾盾"],
    menpai: "苍云",
    icon: "fenshan.png",
    color: "#b43c00",
    type: ["dps", "外功", "身法"],
  },
  tiegu: {
    name: "铁骨衣",
    nickname: ["苍云T", "铁骨衣", "铁骨"],
    menpai: "苍云",
    icon: "tiegu.png",
    color: "#b43c00",
    type: ["T"],
  },
  mowen: {
    name: "莫问",
    nickname: ["莫问", "长歌", "鸽子", "咕咕"],
    menpai: "长歌",
    icon: "mowen.png",
    color: "#64fab4",
    type: ["dps", "内功", "根骨"],
  },
  xiangzhi: {
    name: "相知",
    nickname: ["奶歌", "相知", "歌奶", "奶鸽", "鸽奶", "奶咕", "咕奶"],
    menpai: "长歌",
    icon: "xiangzhi.png",
    color: "#64fab4",
    type: ["奶妈"],
  },
  beiao: {
    name: "北傲诀",
    nickname: ["霸刀", "北傲诀", "貂貂"],
    menpai: "霸刀",
    icon: "beiao.png",
    color: "#6a6cbd",
    type: ["dps", "外功", "力道"],
  },
  linghai: {
    name: "凌海诀",
    nickname: ["蓬莱", "凌海诀", "凌海决", "伞"],
    menpai: "蓬莱",
    icon: "linghai.png",
    color: "#abe3fa",
    type: ["dps", "外功", "身法"],
  },
  yinlong: {
    name: "隐龙诀",
    nickname: ["凌雪", "凌血", "0雪", "隐龙诀", "隐龙决", "凌雪阁", "凌血阁"],
    menpai: "凌雪",
    icon: "yinlong.png",
    color: "#a10922",
    type: ["dps", "外功", "身法"],
  },
  taixuan: {
    name: "太玄经",
    nickname: ["衍天", "太玄经", "衍天宗", "灯灯", "算卦的"],
    menpai: "衍天",
    icon: "taixuan.png",
    color: "#a653fb",
    type: ["dps", "内功", "元气"],
  },
  wufang: {
    name: "无方",
    nickname: ["无方", "药宗", "药药"],
    menpai: "药宗",
    icon: "wufang.png",
    color: "#00ac99",
    type: ["dps", "内功", "根骨"],
  },
  lingsu: {
    name: "灵素",
    nickname: ["奶药", "药奶", "灵素"],
    menpai: "药宗",
    icon: "lingsu.png",
    color: "#00ac99",
    type: ["奶妈"],
  },
  gufeng: {
    name: "孤峰诀",
    nickname: ["刀宗", "孤峰诀", "孤峰决"],
    menpai: "刀宗",
    icon: "gufeng.png",
    color: "#6bb7f2",
    type: ["dps", "外功", "力道"],
  },
  shanhai: {
    name: "山海心诀",
    nickname: ["万灵", "山海心诀", "弓"],
    menpai: "万灵",
    icon: "shanhai.png",
    color: "#ebd773",
    type: ["dps", "外功", "身法"],
  },
  zhoutian: {
    name: "周天功",
    nickname: ["段氏", "周天功", "扇子", "扇"],
    menpai: "段氏",
    icon: "zhoutian.png",
    color: "#5F9BB4",
    type: ["dps", "内功", "元气"],
  },
  youluo: {
    name: "幽罗引",
    nickname: ["幽罗", "幽罗引", "无相楼", "无相", "五香楼", "五香", "无相引", "傀儡", "傀儡师", "唱戏的"],
    menpai: "无相楼",
    icon: "youluo.png",
    color: "#695FB9",
    type: ["dps", "内功", "根骨"],
  },
};

export const allXinfaList = Object.keys(xinfaInfoTable);

export const dpsXinfaList = allXinfaList.filter((xinfa) => xinfaInfoTable[xinfa].type.includes("dps"));

export const naiXinfaList = allXinfaList.filter((xinfa) => xinfaInfoTable[xinfa].type.includes("奶妈"));

export const tXinfaList = allXinfaList.filter((xinfa) => xinfaInfoTable[xinfa].type.includes("T"));

export const neigongXinfaList = allXinfaList.filter((xinfa) => xinfaInfoTable[xinfa].type.includes("内功"));

export const waigongXinfaList = allXinfaList.filter((xinfa) => xinfaInfoTable[xinfa].type.includes("外功"));
