"""create bot tables

Revision ID: 97798943a4a1
Revises: 950e2c1cb493
Create Date: 2025-12-30 17:15:35.030033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97798943a4a1'
down_revision: Union[str, None] = '950e2c1cb493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False, comment='Bot ID'),
    sa.Column('bot_name', sa.String(length=50), nullable=False, comment='Bot标识名（唯一）'),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False, comment='API Key哈希值'),
    sa.Column('description', sa.Text(), nullable=True, comment='Bot描述'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='最后使用时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_bot_name'), 'bots', ['bot_name'], unique=True)
    op.create_index(op.f('ix_bots_id'), 'bots', ['id'], unique=False)
    op.create_index(op.f('ix_bots_is_active'), 'bots', ['is_active'], unique=False)
    op.create_table('bot_guilds',
    sa.Column('id', sa.Integer(), nullable=False, comment='关联ID'),
    sa.Column('bot_id', sa.Integer(), nullable=False, comment='Bot ID'),
    sa.Column('guild_id', sa.Integer(), nullable=False, comment='群组ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='授权时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='授权管理员ID'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['system_admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_guilds_bot_id'), 'bot_guilds', ['bot_id'], unique=False)
    op.create_index(op.f('ix_bot_guilds_guild_id'), 'bot_guilds', ['guild_id'], unique=False)
    op.create_index(op.f('ix_bot_guilds_id'), 'bot_guilds', ['id'], unique=False)
    op.create_index('uq_bot_guild', 'bot_guilds', ['bot_id', 'guild_id'], unique=True)
    # op.drop_table('system_configs')  # 注释掉误删的system_configs表
    op.alter_column('gold_records', 'xuanjing_drops',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='玄晶掉落信息（包含价格）',
               existing_nullable=True)
    op.alter_column('gold_records', 'has_xuanjing',
               existing_type=sa.BOOLEAN(),
               comment='是否出玄晶',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('unique_team_id_when_not_null', table_name='gold_records', postgresql_where='((team_id IS NOT NULL) AND (deleted_at IS NULL))')
    op.drop_index('ix_ranking_snapshots_guild_snapshot', table_name='ranking_snapshots')
    op.drop_index('ix_ranking_snapshots_guild_user', table_name='ranking_snapshots')
    op.alter_column('season_correction_factors', 'end_date',
               existing_type=sa.DATE(),
               comment='时间段结束日期（NULL表示永久有效）',
               existing_comment='时间段结束日期',
               existing_nullable=True)
    op.alter_column('signups', 'slot_position',
               existing_type=sa.INTEGER(),
               comment='锁定位置（0-24或null）',
               existing_comment='锁定位置（1-25或null）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signups', 'slot_position',
               existing_type=sa.INTEGER(),
               comment='锁定位置（1-25或null）',
               existing_comment='锁定位置（0-24或null）',
               existing_nullable=True)
    op.alter_column('season_correction_factors', 'end_date',
               existing_type=sa.DATE(),
               comment='时间段结束日期',
               existing_comment='时间段结束日期（NULL表示永久有效）',
               existing_nullable=True)
    op.create_index('ix_ranking_snapshots_guild_user', 'ranking_snapshots', ['guild_id', 'user_id'], unique=False)
    op.create_index('ix_ranking_snapshots_guild_snapshot', 'ranking_snapshots', ['guild_id', 'snapshot_date'], unique=False)
    op.create_index('unique_team_id_when_not_null', 'gold_records', ['team_id'], unique=True, postgresql_where='((team_id IS NOT NULL) AND (deleted_at IS NULL))')
    op.alter_column('gold_records', 'has_xuanjing',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否出玄晶',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('gold_records', 'xuanjing_drops',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='玄晶掉落信息（包含价格）',
               existing_nullable=True)
    op.create_table('system_configs',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='system_configs_pkey')
    )
    op.drop_index('uq_bot_guild', table_name='bot_guilds')
    op.drop_index(op.f('ix_bot_guilds_id'), table_name='bot_guilds')
    op.drop_index(op.f('ix_bot_guilds_guild_id'), table_name='bot_guilds')
    op.drop_index(op.f('ix_bot_guilds_bot_id'), table_name='bot_guilds')
    op.drop_table('bot_guilds')
    op.drop_index(op.f('ix_bots_is_active'), table_name='bots')
    op.drop_index(op.f('ix_bots_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_bot_name'), table_name='bots')
    op.drop_table('bots')
    # ### end Alembic commands ###
