// Code generated by https://github.com/go-dev-frame/sponge

package handler

import (
	"context"
	"encoding/json"
	"net/http"
	"time"

	//"github.com/go-dev-frame/sponge/pkg/gin/middleware"

	XiaoYangV1 "XiaoYang/api/XiaoYang/v1"
	"XiaoYang/internal/cache"
	"XiaoYang/internal/dao"
	"XiaoYang/internal/database"
	"XiaoYang/internal/ecode"
	"XiaoYang/internal/model"
	"XiaoYang/internal/service"
	"XiaoYang/internal/utils"

	"github.com/go-dev-frame/sponge/pkg/logger"
	"github.com/go-dev-frame/sponge/pkg/sgorm/query"
)

var _ XiaoYangV1.TeamServiceLogicer = (*teamServiceHandler)(nil)

type teamServiceHandler struct {
	userDao            dao.UsersDao
	teamServiceDao     dao.TeamsDao
	guildMemberDao     dao.GuildMembersDao
	teamTemplateDao    dao.TeamTemplatesDao
	dungeonStatsDao    dao.DungeonStatsDao
	dungeonStatsService *service.DungeonStatsService
}

// NewTeamServiceHandler create a handler
func NewTeamServiceHandler() XiaoYangV1.TeamServiceLogicer {
	teamsDao := dao.NewTeamsDao(
		database.GetDB(),
		cache.NewTeamsCache(database.GetCacheType()),
	)
	dungeonStatsDao := dao.NewDungeonStatsDao(
		database.GetDB(),
		cache.NewDungeonStatsCache(database.GetCacheType()),
	)

	return &teamServiceHandler{
		userDao: dao.NewUsersDao(
			database.GetDB(),
			cache.NewUsersCache(database.GetCacheType()),
		),
		teamServiceDao: teamsDao,
		teamTemplateDao: dao.NewTeamTemplatesDao(
			database.GetDB(),
			cache.NewTeamTemplatesCache(database.GetCacheType()),
		),
		guildMemberDao: dao.NewGuildMembersDao(
			database.GetDB(),
			cache.NewGuildMembersCache(database.GetCacheType()),
		),
		dungeonStatsDao:     dungeonStatsDao,
		dungeonStatsService: service.NewDungeonStatsService(teamsDao, dungeonStatsDao),
	}
}

// CreateTeam 开团
func (h *teamServiceHandler) CreateTeam(ctx context.Context, req *XiaoYangV1.CreateTeamRequest) (*XiaoYangV1.CreateTeamResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.ErrCreateTeamTeamService.Err("请求参数无效: " + err.Error())
	}

	data := &model.Teams{
		GuildID:      int(req.GuildId),
		CreaterID:    int(req.CreaterId),
		Title:        req.Title,
		Dungeons:     req.Dungeons,
		BookXuanjing: req.BookXuanjing,
		BookYuntie:   req.BookYuntie,
		IsHidden:     req.IsHidden,
		IsLock:       req.IsLock,
		Rule:         utils.StringToJSONPtr(req.Rule),
		Notice:       req.Notice,
		TeamTime:     utils.ISO8601ToTimePtr(req.TeamTime),
		CreateTime:   utils.NowUTCPointer(),
		UpdateTime:   utils.NowUTCPointer(),
	}

	err = h.teamServiceDao.Create(ctx, data)
	if err != nil {
		logger.Warn("CreateTeam error", logger.Err(err))
		return nil, ecode.ErrCreateTeamTeamService.Err("创建团队失败: " + err.Error())
	}

	return &XiaoYangV1.CreateTeamResponse{
		TeamId: data.ID,
	}, nil
}

// CloseTeam 关闭团队
func (h *teamServiceHandler) CloseTeam(ctx context.Context, req *XiaoYangV1.CloseTeamRequest) (*XiaoYangV1.CloseTeamResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.ErrCloseTeamTeamService.Err("请求参数无效: " + err.Error())
	}

	data, err := h.teamServiceDao.GetByID(ctx, req.TeamId)
	if err != nil {
		logger.Warn("GetByID error", logger.Err(err))
		return nil, ecode.ErrCloseTeamTeamService.Err("获取团队信息失败: " + err.Error())
	}

	data.CloseID = int(req.CloseId)
	data.Summary = utils.StringToJSONPtr(req.Summary)

	// 检查是否为修改模式（通过解析Summary中的isEdit字段判断）
	var summaryMap map[string]interface{}
	if err := json.Unmarshal([]byte(req.Summary), &summaryMap); err == nil {
		if isEdit, exists := summaryMap["isEdit"]; !exists || !isEdit.(bool) {
			// 不是修改模式，更新时间字段
			data.CloseTime = utils.NowUTCPointer()
			data.UpdateTime = utils.NowUTCPointer()
		}
		// 移除isEdit字段，不存储到数据库
		delete(summaryMap, "isEdit")
		if updatedSummary, err := json.Marshal(summaryMap); err == nil {
			data.Summary = utils.StringToJSONPtr(string(updatedSummary))
		}
	} else {
		// 解析失败，按原逻辑处理
		data.CloseTime = utils.NowUTCPointer()
		data.UpdateTime = utils.NowUTCPointer()
	}

	err = h.teamServiceDao.UpdateByID(ctx, data)
	if err != nil {
		logger.Warn("UpdateByID error", logger.Err(err))
		return nil, ecode.ErrCloseTeamTeamService.Err("关闭团队失败: " + err.Error())
	}

	// 异步更新统计数据
	go func() {
		bgCtx := context.Background()
		if err := h.dungeonStatsService.UpdateStatsForTeam(bgCtx, data.GuildID, data.Dungeons); err != nil {
			logger.Warn("Failed to update dungeon stats", logger.Err(err),
				logger.Any("guildId", data.GuildID),
				logger.Any("dungeonName", data.Dungeons))
		}
	}()

	return &XiaoYangV1.CloseTeamResponse{Success: true}, nil
}

// UpdateTeam 修改开团信息
func (h *teamServiceHandler) UpdateTeam(ctx context.Context, req *XiaoYangV1.UpdateTeamRequest) (*XiaoYangV1.UpdateTeamResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.ErrUpdateTeamTeamService.Err("请求参数无效: " + err.Error())
	}

	data, err := h.teamServiceDao.GetByID(ctx, req.TeamId)
	if err != nil {
		logger.Warn("GetByID error", logger.Err(err))
		return nil, ecode.ErrUpdateTeamTeamService.Err("获取团队信息失败: " + err.Error())
	}

	// 保存旧的副本名称，用于检测是否改变
	oldDungeon := data.Dungeons
	oldGuildID := data.GuildID

	// 更新字段
	data.Title = req.Title
	data.Dungeons = req.Dungeons
	data.BookXuanjing = req.BookXuanjing
	data.BookYuntie = req.BookYuntie
	data.IsHidden = req.IsHidden
	data.IsLock = req.IsLock
	data.Rule = utils.StringToJSONPtr(req.Rule)
	data.Notice = req.Notice
	data.TeamTime = utils.ISO8601ToTimePtr(req.TeamTime)
	data.UpdateTime = utils.NowUTCPointer()

	err = h.teamServiceDao.UpdateByID(ctx, data)
	if err != nil {
		logger.Warn("UpdateByID error", logger.Err(err))
		return nil, ecode.ErrUpdateTeamTeamService.Err("更新团队信息失败: " + err.Error())
	}

	// 如果副本名称改变了且团队已关闭（有summary），需要更新两个副本的统计数据
	if oldDungeon != data.Dungeons && data.CloseTime != nil && data.Summary != nil {
		go func() {
			bgCtx := context.Background()
			// 更新旧副本的统计
			if err := h.dungeonStatsService.UpdateStatsForTeam(bgCtx, oldGuildID, oldDungeon); err != nil {
				logger.Warn("Failed to update old dungeon stats", logger.Err(err),
					logger.Any("guildId", oldGuildID),
					logger.Any("oldDungeonName", oldDungeon))
			}
			// 更新新副本的统计
			if err := h.dungeonStatsService.UpdateStatsForTeam(bgCtx, data.GuildID, data.Dungeons); err != nil {
				logger.Warn("Failed to update new dungeon stats", logger.Err(err),
					logger.Any("guildId", data.GuildID),
					logger.Any("newDungeonName", data.Dungeons))
			}
		}()
	}

	return &XiaoYangV1.UpdateTeamResponse{Success: true}, nil
}

// CreateTemplate 新增模板
func (h *teamServiceHandler) CreateTemplate(ctx context.Context, req *XiaoYangV1.CreateTemplateRequest) (*XiaoYangV1.CreateTemplateResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.ErrCreateTemplateTeamService.Err("请求参数无效: " + err.Error())
	}

	data := &model.TeamTemplates{
		GuildID:   int(req.GuildId),
		CreaterID: int(req.CreaterId),
		Title:     req.Title,
		Rule:      utils.StringToJSONPtr(req.Rule),
		Notice:    req.Notice,
	}

	err = h.teamTemplateDao.Create(ctx, data)
	if err != nil {
		logger.Warn("CreateTemplate error", logger.Err(err))
		return nil, ecode.ErrCreateTemplateTeamService.Err("创建模板失败: " + err.Error())
	}

	return &XiaoYangV1.CreateTemplateResponse{
		TemplateId: data.ID,
	}, nil
}

// DeleteTemplate 删除模板
func (h *teamServiceHandler) DeleteTemplate(ctx context.Context, req *XiaoYangV1.DeleteTemplateRequest) (*XiaoYangV1.DeleteTemplateResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.ErrDeleteTemplateTeamService.Err("请求参数无效: " + err.Error())
	}

	err = h.teamTemplateDao.DeleteByID(ctx, req.TemplateId)
	if err != nil {
		logger.Warn("DeleteTemplate error", logger.Err(err))
		return nil, ecode.ErrDeleteTemplateTeamService.Err("删除模板失败: " + err.Error())
	}

	return &XiaoYangV1.DeleteTemplateResponse{Success: true}, nil
}

// UpdateTemplate 修改模板
func (h *teamServiceHandler) UpdateTemplate(ctx context.Context, req *XiaoYangV1.UpdateTemplateRequest) (*XiaoYangV1.UpdateTemplateResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.ErrUpdateTemplateTeamService.Err("请求参数无效: " + err.Error())
	}

	data, err := h.teamTemplateDao.GetByID(ctx, req.TemplateId)
	if err != nil {
		logger.Warn("GetTemplateByID error", logger.Err(err))
		return nil, ecode.ErrUpdateTemplateTeamService.Err("获取模板信息失败: " + err.Error())
	}

	// 更新字段
	data.Title = req.Title
	data.Rule = utils.StringToJSONPtr(req.Rule)
	data.Notice = req.Notice

	err = h.teamTemplateDao.UpdateByID(ctx, data)
	if err != nil {
		logger.Warn("UpdateTemplateByID error", logger.Err(err))
		return nil, ecode.ErrUpdateTemplateTeamService.Err("更新模板信息失败: " + err.Error())
	}

	return &XiaoYangV1.UpdateTemplateResponse{Success: true}, nil
}

// GetTeam 获取开团信息
func (h *teamServiceHandler) GetTeam(ctx context.Context, req *XiaoYangV1.GetTeamRequest) (*XiaoYangV1.GetTeamResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.ErrGetTeamTeamService.Err("请求参数无效: " + err.Error())
	}

	data, err := h.teamServiceDao.GetByID(ctx, req.TeamId)
	if err != nil {
		logger.Warn("GetByID error", logger.Err(err))
		return nil, ecode.ErrGetTeamTeamService.Err("获取团队信息失败: " + err.Error())
	}

	createrNickname, closeNickname, err := h.getNicknames(ctx, data.CreaterID, data.CloseID, data.CloseTime)
	if err != nil {
		return nil, ecode.ErrGetTeamTeamService.Err("获取用户信息失败: " + err.Error())
	}

	return &XiaoYangV1.GetTeamResponse{
		TeamInfo: &XiaoYangV1.TeamInfo{
			TeamId:          data.ID,
			GuildId:         uint64(data.GuildID),
			CreaterId:       uint64(data.CreaterID),
			CreaterNickname: createrNickname,
			Title:           data.Title,
			Dungeons:        data.Dungeons,
			BookXuanjing:    data.BookXuanjing,
			BookYuntie:      data.BookYuntie,
			IsHidden:        data.IsHidden,
			IsLock:          data.IsLock,
			Rule:            utils.JSONPtrToString(data.Rule),
			Notice:          data.Notice,
			Summary:         utils.JSONPtrToString(data.Summary),
			TeamTime:        utils.TimePtrToISO8601(data.TeamTime),
			CreateTime:      utils.TimePtrToISO8601(data.CreateTime),
			UpdateTime:      utils.TimePtrToISO8601(data.UpdateTime),
			CloseTime:       utils.TimePtrToISO8601(data.CloseTime),
			CloseId:         uint64(data.CloseID),
			CloseNickname:   closeNickname,
		},
	}, nil
}

// ListTeams 获取所有开团信息
func (h *teamServiceHandler) ListTeams(ctx context.Context, req *XiaoYangV1.ListTeamsRequest) (*XiaoYangV1.ListTeamsResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.ErrListTeamsTeamService.Err("请求参数无效: " + err.Error())
	}

	params := &query.Params{
		Columns: []query.Column{
			{
				Name:  "guild_id",
				Exp:   query.Eq,
				Value: req.GuildId,
			},
		},
		Page:  int(req.Page),
		Limit: int(req.PageSize),
	}

	if req.Filter == "only_open" {
		params.Columns = append(params.Columns, query.Column{
			Name: "close_time",
			Exp:  query.IsNull,
		})
	} else if req.Filter == "only_close" {
		params.Columns = append(params.Columns, query.Column{
			Name: "close_time",
			Exp:  query.IsNotNull,
		})
	}

	auth := ctx.Value("request_header_key").(http.Header).Get("Authorization")
	userInfo, err := utils.ParseToken(auth)
	if err != nil {
		logger.Warn("ParseToken error", logger.Err(err))
		return nil, ecode.ErrGetUserInfoUserService.Err("Token解析失败: " + err.Error())
	}

	// 检查用户权限
	if !userInfo.IsAdmin && !userInfo.IsBot {
		member, _, err := h.guildMemberDao.GetByColumns(ctx, &query.Params{
			Columns: []query.Column{
				{Name: "guild_id",
					Exp:   query.Eq,
					Value: req.GuildId},
				{Name: "member_id",
					Exp:   query.Eq,
					Value: userInfo.UserID},
			},
		})
		if err != nil || len(member) == 0 || (member[0].Role != "owner" && member[0].Role != "helper") {
			params.Columns = append(params.Columns, query.Column{
				Name:  "is_hidden",
				Exp:   query.Eq,
				Value: false,
			})
		}
	}

	data, _, err := h.teamServiceDao.GetByColumns(ctx, params)
	if err != nil {
		logger.Warn("GetByColumns error", logger.Err(err))
		return nil, ecode.ErrListTeamsTeamService.Err("获取团队列表失败: " + err.Error())
	}

	teams := make([]*XiaoYangV1.TeamInfo, len(data))
	for i, team := range data {
		createrNickname, closeNickname, err := h.getNicknames(ctx, team.CreaterID, team.CloseID, team.CloseTime)
		if err != nil {
			return nil, ecode.ErrListTeamsTeamService.Err("获取用户信息失败: " + err.Error())
		}

		teams[i] = &XiaoYangV1.TeamInfo{
			TeamId:          team.ID,
			GuildId:         uint64(team.GuildID),
			CreaterId:       uint64(team.CreaterID),
			CreaterNickname: createrNickname,
			Title:           team.Title,
			Dungeons:        team.Dungeons,
			BookXuanjing:    team.BookXuanjing,
			BookYuntie:      team.BookYuntie,
			IsHidden:        team.IsHidden,
			IsLock:          team.IsLock,
			Rule:            utils.JSONPtrToString(team.Rule),
			Notice:          team.Notice,
			Summary:         utils.JSONPtrToString(team.Summary),
			TeamTime:        utils.TimePtrToISO8601(team.TeamTime),
			CreateTime:      utils.TimePtrToISO8601(team.CreateTime),
			UpdateTime:      utils.TimePtrToISO8601(team.UpdateTime),
			CloseTime:       utils.TimePtrToISO8601(team.CloseTime),
			CloseId:         uint64(team.CloseID),
			CloseNickname:   closeNickname,
		}
	}

	return &XiaoYangV1.ListTeamsResponse{Teams: teams}, nil
}

// GetTemplate 获取模板信息
func (h *teamServiceHandler) GetTemplate(ctx context.Context, req *XiaoYangV1.GetTemplateRequest) (*XiaoYangV1.GetTemplateResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.ErrGetTemplateTeamService.Err("请求参数无效: " + err.Error())
	}

	data, err := h.teamTemplateDao.GetByID(ctx, req.TemplateId)
	if err != nil {
		logger.Warn("GetTemplateByID error", logger.Err(err))
		return nil, ecode.ErrGetTemplateTeamService.Err("获取模板信息失败: " + err.Error())
	}

	return &XiaoYangV1.GetTemplateResponse{
		TemplateInfo: &XiaoYangV1.TemplateInfo{
			TemplateId: data.ID,
			GuildId:    uint64(data.GuildID),
			CreaterId:  uint64(data.CreaterID),
			Title:      data.Title,
			Rule:       utils.JSONPtrToString(data.Rule),
			Notice:     data.Notice,
		},
	}, nil
}

// ListTemplates 获取所有模板信息
func (h *teamServiceHandler) ListTemplates(ctx context.Context, req *XiaoYangV1.ListTemplatesRequest) (*XiaoYangV1.ListTemplatesResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.ErrListTemplatesTeamService.Err("请求参数无效: " + err.Error())
	}

	params := &query.Params{
		Columns: []query.Column{
			{
				Name:  "guild_id",
				Exp:   query.Eq,
				Value: req.GuildId,
			},
		},
		Page:  0,
		Limit: 99999,
	}

	data, _, err := h.teamTemplateDao.GetByColumns(ctx, params)
	if err != nil {
		logger.Warn("GetByColumns error", logger.Err(err))
		return nil, ecode.ErrListTemplatesTeamService.Err("获取模板列表失败: " + err.Error())
	}

	templates := make([]*XiaoYangV1.TemplateInfo, len(data))
	for i, template := range data {
		templates[i] = &XiaoYangV1.TemplateInfo{
			TemplateId: template.ID,
			GuildId:    uint64(template.GuildID),
			CreaterId:  uint64(template.CreaterID),
			Title:      template.Title,
			Rule:       utils.JSONPtrToString(template.Rule),
			Notice:     template.Notice,
		}
	}

	return &XiaoYangV1.ListTemplatesResponse{Templates: templates}, nil
}

// GetDungeonStats 获取副本统计数据
func (h *teamServiceHandler) GetDungeonStats(ctx context.Context, req *XiaoYangV1.GetDungeonStatsRequest) (*XiaoYangV1.GetDungeonStatsResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.StatusInvalidParams.Err("请求参数无效: " + err.Error())
	}

	var stats []*model.DungeonStats

	if req.DungeonName != "" {
		// 获取指定副本的统计数据
		stat, err := h.dungeonStatsService.GetStatsByGuildAndDungeon(ctx, int(req.GuildId), req.DungeonName)
		if err != nil {
			logger.Warn("GetStatsByGuildAndDungeon error", logger.Err(err))
			// 如果统计数据不存在，返回空列表而不是错误
			return &XiaoYangV1.GetDungeonStatsResponse{Stats: []*XiaoYangV1.DungeonStatsInfo{}}, nil
		}
		stats = []*model.DungeonStats{stat}
	} else {
		// 获取该公会所有副本的统计数据
		stats, err = h.dungeonStatsService.GetAllStatsByGuild(ctx, int(req.GuildId))
		if err != nil {
			logger.Warn("GetAllStatsByGuild error", logger.Err(err))
			return nil, ecode.StatusInternalServerError.Err("获取统计数据失败: " + err.Error())
		}
	}

	// 转换为响应格式
	statsInfo := make([]*XiaoYangV1.DungeonStatsInfo, len(stats))
	for i, stat := range stats {
		minTeamID := uint64(0)
		if stat.MinSalaryTeamID != nil {
			minTeamID = uint64(*stat.MinSalaryTeamID)
		}
		maxTeamID := uint64(0)
		if stat.MaxSalaryTeamID != nil {
			maxTeamID = uint64(*stat.MaxSalaryTeamID)
		}

		statsInfo[i] = &XiaoYangV1.DungeonStatsInfo{
			Id:                   stat.ID,
			GuildId:              uint64(stat.GuildID),
			DungeonName:          stat.DungeonName,
			TotalCount:           int32(stat.TotalCount),
			MinSalary:            int32(stat.MinSalary),
			MaxSalary:            int32(stat.MaxSalary),
			AvgSalary:            stat.AvgSalary,
			MinPerPersonSalary:   int32(stat.MinPerPersonSalary),
			MaxPerPersonSalary:   int32(stat.MaxPerPersonSalary),
			AvgPerPersonSalary:   stat.AvgPerPersonSalary,
			MinSalaryTeamId:      minTeamID,
			MaxSalaryTeamId:      maxTeamID,
			CreateTime:           utils.TimePtrToISO8601(stat.CreateTime),
			UpdateTime:           utils.TimePtrToISO8601(stat.UpdateTime),
		}
	}

	return &XiaoYangV1.GetDungeonStatsResponse{Stats: statsInfo}, nil
}

func (h *teamServiceHandler) getNicknames(ctx context.Context, createrID, closeID int, closeTime *time.Time) (string, string, error) {
	createrUserInfo, err := h.userDao.GetByID(ctx, uint64(createrID))
	if err != nil {
		logger.Warn("GetUserByID error", logger.Err(err))
		return "", "", err
	}

	createrNickname := ""
	if createrUserInfo != nil {
		createrNickname = createrUserInfo.Nickname
	}

	closeNickname := ""
	if closeTime != nil {
		closeUserInfo, err := h.userDao.GetByID(ctx, uint64(closeID))
		if err != nil {
			logger.Warn("GetUserByID error", logger.Err(err))
			return "", "", err
		}
		if closeUserInfo != nil {
			closeNickname = closeUserInfo.Nickname
		}
	}

	return createrNickname, closeNickname, nil
}
