// Code generated by https://github.com/go-dev-frame/sponge

package handler

import (
	"context"
	"net/http"

	//"github.com/go-dev-frame/sponge/pkg/gin/middleware"

	XiaoYangV1 "XiaoYang/api/XiaoYang/v1"
	"XiaoYang/internal/cache"
	"XiaoYang/internal/dao"
	"XiaoYang/internal/database"
	"XiaoYang/internal/ecode"
	"XiaoYang/internal/model"
	"XiaoYang/internal/utils"

	"github.com/go-dev-frame/sponge/pkg/gocrypto"
	"github.com/go-dev-frame/sponge/pkg/jwt"
	"github.com/go-dev-frame/sponge/pkg/logger"
)

var _ XiaoYangV1.UserServiceLogicer = (*userServiceHandler)(nil)

type userServiceHandler struct {
	userDao dao.UsersDao
}

// NewUserServiceHandler create a handler
func NewUserServiceHandler() XiaoYangV1.UserServiceLogicer {
	return &userServiceHandler{
		userDao: dao.NewUsersDao(
			database.GetDB(),
			cache.NewUsersCache(database.GetCacheType()),
		),
	}
}

// Register 注册
func (h *userServiceHandler) Register(ctx context.Context, req *XiaoYangV1.RegisterRequest) (*XiaoYangV1.RegisterResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.ErrRegisterUserService.Err("请求参数无效，请检查输入")
	}

	pswd, err := gocrypto.HashAndSaltPassword(req.Password)
	if err != nil {
		logger.Warn("HashAndSaltPassword error", logger.Err(err))
		return nil, ecode.InternalServerError.Err("密码加密失败: " + err.Error())
	}

	data := &model.Users{
		QqNumber: req.QqNumber,
		Password: pswd,
		Nickname: req.Nickname,
	}

	err = h.userDao.Create(ctx, data)
	if err != nil {
		logger.Warn("Register error", logger.Err(err))
		return nil, ecode.ErrRegisterUserService.Err("注册失败: " + err.Error())
	}

	fields := jwt.KV{
		"userId":   data.ID,
		"qqNumber": data.QqNumber,
		"nickname": data.Nickname,
		"isAdmin":  data.IsAdmin,
		"isBot":    data.IsBot,
	}
	token, err := jwt.GenerateCustomToken(fields)
	if err != nil {
		logger.Warn("GenerateToken error", logger.Err(err))
		return nil, ecode.InternalServerError.Err("生成Token失败: " + err.Error())
	}

	return &XiaoYangV1.RegisterResponse{
		Token:    token,
		UserId:   data.ID,
		QqNumber: data.QqNumber,
		Nickname: data.Nickname,
		Avatar:   data.Avatar,
	}, nil
}

// Login 登录
func (h *userServiceHandler) Login(ctx context.Context, req *XiaoYangV1.LoginRequest) (*XiaoYangV1.LoginResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.ErrLoginUserService.Err("请求参数无效: " + err.Error())
	}

	data, err := h.userDao.GetByQqNumber(ctx, req.QqNumber)
	if err != nil {
		logger.Warn("GetByQqNumber error", logger.Err(err))
		return nil, ecode.ErrLoginUserService.Err("用户未注册: " + err.Error())
	}

	if !gocrypto.VerifyPassword(req.Password, data.Password) {
		logger.Warn("password error", logger.Err(err))
		return nil, ecode.ErrLoginUserService.Err("密码错误")
	}

	fields := jwt.KV{
		"userId":   data.ID,
		"qqNumber": data.QqNumber,
		"nickname": data.Nickname,
		"isAdmin":  data.IsAdmin,
		"isBot":    data.IsBot,
	}
	token, err := jwt.GenerateCustomToken(fields)
	if err != nil {
		logger.Warn("GenerateToken error", logger.Err(err))
		return nil, ecode.ErrLoginUserService.Err("生成Token失败: " + err.Error())
	}

	return &XiaoYangV1.LoginResponse{
		Token:    token,
		UserId:   data.ID,
		QqNumber: data.QqNumber,
		Nickname: data.Nickname,
		Avatar:   data.Avatar,
	}, nil
}

// Logout 登出
func (h *userServiceHandler) Logout(ctx context.Context, req *XiaoYangV1.LogoutRequest) (*XiaoYangV1.LogoutResponse, error) {
	// 不需要做任何事情，直接返回成功
	return &XiaoYangV1.LogoutResponse{}, nil
}

// GetUserInfo 获取用户信息
func (h *userServiceHandler) GetUserInfo(ctx context.Context, req *XiaoYangV1.GetUserInfoRequest) (*XiaoYangV1.GetUserInfoResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.ErrGetUserInfoUserService.Err("请求参数无效: " + err.Error())
	}

	auth := ctx.Value("request_header_key").(http.Header).Get("Authorization")
	userInfo, err := utils.ParseToken(auth)
	if err != nil {
		logger.Warn("ParseToken error", logger.Err(err))
		return nil, ecode.ErrGetUserInfoUserService.Err("Token解析失败: " + err.Error())
	}

	data, err := h.userDao.GetByID(ctx, uint64(userInfo.UserID))
	if err != nil {
		logger.Warn("GetUserInfo error", logger.Err(err))
		return nil, ecode.ErrGetUserInfoUserService.Err("获取用户信息失败: " + err.Error())
	}

	return &XiaoYangV1.GetUserInfoResponse{
		UserId:   data.ID,
		QqNumber: data.QqNumber,
		Nickname: data.Nickname,
		Avatar:   data.Avatar,
		IsAdmin:  data.IsAdmin,
	}, nil

}

// UpdateUserInfo 更新用户信息
func (h *userServiceHandler) UpdateUserInfo(ctx context.Context, req *XiaoYangV1.UpdateUserInfoRequest) (*XiaoYangV1.UpdateUserInfoResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.ErrUpdateUserInfoUserService.Err("请求参数无效: " + err.Error())
	}

	data, err := h.userDao.GetByID(ctx, req.UserId)
	if err != nil {
		logger.Warn("GetByID error", logger.Err(err))
		return nil, ecode.ErrUpdateUserInfoUserService.Err("用户不存在: " + err.Error())
	}

	if req.Nickname != "" {
		data.Nickname = req.Nickname
	}
	if req.Avatar != "" {
		data.Avatar = req.Avatar
	}

	err = h.userDao.UpdateByID(ctx, data)
	if err != nil {
		logger.Warn("UpdateByID error", logger.Err(err))
		return nil, ecode.ErrUpdateUserInfoUserService.Err("更新用户信息失败: " + err.Error())
	}

	return &XiaoYangV1.UpdateUserInfoResponse{}, nil
}

// ChangePassword 修改密码
func (h *userServiceHandler) ChangePassword(ctx context.Context, req *XiaoYangV1.ChangePasswordRequest) (*XiaoYangV1.ChangePasswordResponse, error) {
	err := req.Validate()
	if err != nil {
		logger.Warn("req.Validate error", logger.Err(err))
		return nil, ecode.ErrChangePasswordUserService.Err("请求参数无效: " + err.Error())
	}

	data, err := h.userDao.GetByID(ctx, req.UserId)
	if err != nil {
		logger.Warn("GetByID error", logger.Err(err))
		return nil, ecode.ErrChangePasswordUserService.Err("用户不存在: " + err.Error())
	}

	if !gocrypto.VerifyPassword(req.OldPassword, data.Password) {
		logger.Warn("OldPassword error", logger.Err(err))
		return nil, ecode.ErrChangePasswordUserService.Err("旧密码错误")
	}

	newPassword, err := gocrypto.HashAndSaltPassword(req.NewPassword)
	if err != nil {
		logger.Warn("HashAndSaltPassword error", logger.Err(err))
		return nil, ecode.InternalServerError.Err("密码加密失败: " + err.Error())
	}

	data.Password = newPassword
	err = h.userDao.UpdateByID(ctx, data)
	if err != nil {
		logger.Warn("Update error", logger.Err(err))
		return nil, ecode.ErrChangePasswordUserService.Err("更新密码失败: " + err.Error())
	}

	return &XiaoYangV1.ChangePasswordResponse{}, nil
}
