// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/go-dev-frame/sponge/pkg/errcode"
	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
)

type CharacterServiceLogicer interface {
	CreateCharacter(ctx context.Context, req *CreateCharacterRequest) (*CreateCharacterResponse, error)
	UpdateCharacter(ctx context.Context, req *UpdateCharacterRequest) (*UpdateCharacterResponse, error)
	DeleteCharacter(ctx context.Context, req *DeleteCharacterRequest) (*DeleteCharacterResponse, error)
	GetCharacter(ctx context.Context, req *GetCharacterRequest) (*GetCharacterResponse, error)
	ListUserCharacters(ctx context.Context, req *ListUserCharactersRequest) (*ListUserCharactersResponse, error)
}

type CharacterServiceOption func(*characterServiceOptions)

type characterServiceOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *characterServiceOptions) apply(opts ...CharacterServiceOption) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithCharacterServiceHTTPResponse() CharacterServiceOption {
	return func(o *characterServiceOptions) {
		o.isFromRPC = false
	}
}

func WithCharacterServiceRPCResponse() CharacterServiceOption {
	return func(o *characterServiceOptions) {
		o.isFromRPC = true
	}
}

func WithCharacterServiceResponser(responser errcode.Responser) CharacterServiceOption {
	return func(o *characterServiceOptions) {
		o.responser = responser
	}
}

func WithCharacterServiceLogger(zapLog *zap.Logger) CharacterServiceOption {
	return func(o *characterServiceOptions) {
		o.zapLog = zapLog
	}
}

func WithCharacterServiceErrorToHTTPCode(e ...*errcode.Error) CharacterServiceOption {
	return func(o *characterServiceOptions) {
		o.httpErrors = e
	}
}

func WithCharacterServiceRPCStatusToHTTPCode(s ...*errcode.RPCStatus) CharacterServiceOption {
	return func(o *characterServiceOptions) {
		o.rpcStatus = s
	}
}

func WithCharacterServiceWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) CharacterServiceOption {
	return func(o *characterServiceOptions) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func RegisterCharacterServiceRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic CharacterServiceLogicer,
	opts ...CharacterServiceOption) {

	o := &characterServiceOptions{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isFromRPC, o.httpErrors, o.rpcStatus)
	}
	if o.zapLog == nil {
		o.zapLog, _ = zap.NewProduction()
	}

	r := &characterServiceRouter{
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		zapLog:                o.zapLog,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type characterServiceRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                CharacterServiceLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *characterServiceRouter) register() {
	r.iRouter.Handle("POST", "/api/v1/character/createCharacter", r.withMiddleware("POST", "/api/v1/character/createCharacter", r.CreateCharacter_0)...)
	r.iRouter.Handle("POST", "/api/v1/character/updateCharacter", r.withMiddleware("POST", "/api/v1/character/updateCharacter", r.UpdateCharacter_0)...)
	r.iRouter.Handle("POST", "/api/v1/character/deleteCharacter", r.withMiddleware("POST", "/api/v1/character/deleteCharacter", r.DeleteCharacter_0)...)
	r.iRouter.Handle("POST", "/api/v1/character/getCharacter", r.withMiddleware("POST", "/api/v1/character/getCharacter", r.GetCharacter_0)...)
	r.iRouter.Handle("POST", "/api/v1/character/listUserCharacters", r.withMiddleware("POST", "/api/v1/character/listUserCharacters", r.ListUserCharacters_0)...)

}

func (r *characterServiceRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

func (r *characterServiceRouter) CreateCharacter_0(c *gin.Context) {
	req := &CreateCharacterRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.CreateCharacter(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *characterServiceRouter) UpdateCharacter_0(c *gin.Context) {
	req := &UpdateCharacterRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.UpdateCharacter(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *characterServiceRouter) DeleteCharacter_0(c *gin.Context) {
	req := &DeleteCharacterRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteCharacter(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *characterServiceRouter) GetCharacter_0(c *gin.Context) {
	req := &GetCharacterRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetCharacter(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *characterServiceRouter) ListUserCharacters_0(c *gin.Context) {
	req := &ListUserCharactersRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.ListUserCharacters(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}
