// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/go-dev-frame/sponge/pkg/errcode"
	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
)

type SignupServiceLogicer interface {
	CreateSignup(ctx context.Context, req *CreateSignupRequest) (*CreateSignupResponse, error)
	CancelSignup(ctx context.Context, req *CancelSignupRequest) (*CancelSignupResponse, error)
	GetSignupsByTeam(ctx context.Context, req *GetSignupsByTeamRequest) (*GetSignupsByTeamResponse, error)
}

type SignupServiceOption func(*signupServiceOptions)

type signupServiceOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *signupServiceOptions) apply(opts ...SignupServiceOption) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithSignupServiceHTTPResponse() SignupServiceOption {
	return func(o *signupServiceOptions) {
		o.isFromRPC = false
	}
}

func WithSignupServiceRPCResponse() SignupServiceOption {
	return func(o *signupServiceOptions) {
		o.isFromRPC = true
	}
}

func WithSignupServiceResponser(responser errcode.Responser) SignupServiceOption {
	return func(o *signupServiceOptions) {
		o.responser = responser
	}
}

func WithSignupServiceLogger(zapLog *zap.Logger) SignupServiceOption {
	return func(o *signupServiceOptions) {
		o.zapLog = zapLog
	}
}

func WithSignupServiceErrorToHTTPCode(e ...*errcode.Error) SignupServiceOption {
	return func(o *signupServiceOptions) {
		o.httpErrors = e
	}
}

func WithSignupServiceRPCStatusToHTTPCode(s ...*errcode.RPCStatus) SignupServiceOption {
	return func(o *signupServiceOptions) {
		o.rpcStatus = s
	}
}

func WithSignupServiceWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) SignupServiceOption {
	return func(o *signupServiceOptions) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func RegisterSignupServiceRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic SignupServiceLogicer,
	opts ...SignupServiceOption) {

	o := &signupServiceOptions{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isFromRPC, o.httpErrors, o.rpcStatus)
	}
	if o.zapLog == nil {
		o.zapLog, _ = zap.NewProduction()
	}

	r := &signupServiceRouter{
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		zapLog:                o.zapLog,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type signupServiceRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                SignupServiceLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *signupServiceRouter) register() {
	r.iRouter.Handle("POST", "/api/v1/signup/createSignup", r.withMiddleware("POST", "/api/v1/signup/createSignup", r.CreateSignup_0)...)
	r.iRouter.Handle("POST", "/api/v1/signup/cancelSignup", r.withMiddleware("POST", "/api/v1/signup/cancelSignup", r.CancelSignup_0)...)
	r.iRouter.Handle("POST", "/api/v1/signup/getSignupsByTeam", r.withMiddleware("POST", "/api/v1/signup/getSignupsByTeam", r.GetSignupsByTeam_0)...)

}

func (r *signupServiceRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

func (r *signupServiceRouter) CreateSignup_0(c *gin.Context) {
	req := &CreateSignupRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.CreateSignup(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *signupServiceRouter) CancelSignup_0(c *gin.Context) {
	req := &CancelSignupRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.CancelSignup(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *signupServiceRouter) GetSignupsByTeam_0(c *gin.Context) {
	req := &GetSignupsByTeamRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetSignupsByTeam(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}
