// Code generated by https://github.com/zhufuyi/sponge

package ecode

import (
	"github.com/zhufuyi/sponge/pkg/errcode"
)

// characterService business-level http error codes.
// the characterServiceNO value range is 1~100, if the same number appears, it will cause a failure to start the service.
var (
	characterServiceNO       = 74
	characterServiceName     = "characterService"
	characterServiceBaseCode = errcode.HCode(characterServiceNO)

	ErrCreateCharacterCharacterService = errcode.NewError(characterServiceBaseCode+1, "failed to CreateCharacter "+characterServiceName)
	ErrListCharacterCharacterService   = errcode.NewError(characterServiceBaseCode+2, "failed to ListCharacter "+characterServiceName)
	ErrDeleteCharacterCharacterService = errcode.NewError(characterServiceBaseCode+3, "failed to DeleteCharacter "+characterServiceName)
	ErrUpdateCharacterCharacterService = errcode.NewError(characterServiceBaseCode+4, "failed to UpdateCharacter "+characterServiceName)
	// error codes are globally unique, adding 1 to the previous error code
)
