// Code generated by https://github.com/zhufuyi/sponge

package ecode

import (
	"github.com/zhufuyi/sponge/pkg/errcode"
)

// teamService business-level http error codes.
// the teamServiceNO value range is 1~100, if the same number appears, it will cause a failure to start the service.
var (
	teamServiceNO       = 18
	teamServiceName     = "teamService"
	teamServiceBaseCode = errcode.HCode(teamServiceNO)

	ErrCreateTeamTeamService         = errcode.NewError(teamServiceBaseCode+1, "failed to CreateTeam "+teamServiceName)
	ErrListTeamTeamService           = errcode.NewError(teamServiceBaseCode+2, "failed to ListTeam "+teamServiceName)
	ErrListActiveTeamTeamService     = errcode.NewError(teamServiceBaseCode+3, "failed to ListActiveTeam "+teamServiceName)
	ErrUpdateTeamTeamService         = errcode.NewError(teamServiceBaseCode+4, "failed to UpdateTeam "+teamServiceName)
	ErrSetTeamVisibleTeamService     = errcode.NewError(teamServiceBaseCode+5, "failed to SetTeamVisible "+teamServiceName)
	ErrSetTeamLockTeamService        = errcode.NewError(teamServiceBaseCode+6, "failed to SetTeamLock "+teamServiceName)
	ErrSetTeamCloseTeamService       = errcode.NewError(teamServiceBaseCode+7, "failed to SetTeamClose "+teamServiceName)
	ErrCreateTeamTemplateTeamService = errcode.NewError(teamServiceBaseCode+8, "failed to CreateTeamTemplate "+teamServiceName)
	ErrListTeamTemplateTeamService   = errcode.NewError(teamServiceBaseCode+9, "failed to ListTeamTemplate "+teamServiceName)
	ErrDeleteTeamTemplateTeamService = errcode.NewError(teamServiceBaseCode+10, "failed to DeleteTeamTemplate "+teamServiceName)
	// error codes are globally unique, adding 1 to the previous error code
)
