version: "3.7"

services:
  xiao-yang:
    image: xiao-yang/xiao-yang:latest
    container_name: xiao-yang
    restart: always
    command: ["./XiaoYang", "-c", "/app/configs/XiaoYang.yml"]
    volumes:
      - $PWD/configs:/app/configs
    ports:
      - "8080:8080"   # http port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]   # http health check, note: mirror must contain curl command

      interval: 10s         # interval time
      timeout: 5s           # timeout time
      retries: 3              # number of retries
      start_period: 10s  # how long after start-up does the check begin
