// Code generated by https://github.com/go-dev-frame/sponge

package ecode

import (
	"github.com/go-dev-frame/sponge/pkg/errcode"
)

// guildService business-level http error codes.
// the guildServiceNO value range is 1~100, if the same error code is used, it will cause panic.
var (
	guildServiceNO       = 21
	guildServiceName     = "guildService"
	guildServiceBaseCode = errcode.HCode(guildServiceNO)

	ErrCreateGuildGuildService       = errcode.NewError(guildServiceBaseCode+1, "failed to CreateGuild "+guildServiceName)
	ErrDeleteGuildGuildService       = errcode.NewError(guildServiceBaseCode+2, "failed to DeleteGuild "+guildServiceName)
	ErrUpdateGuildInfoGuildService   = errcode.NewError(guildServiceBaseCode+3, "failed to UpdateGuildInfo "+guildServiceName)
	ErrGetGuildInfoGuildService      = errcode.NewError(guildServiceBaseCode+4, "failed to GetGuildInfo "+guildServiceName)
	ErrListAllGuildsGuildService     = errcode.NewError(guildServiceBaseCode+5, "failed to ListAllGuilds "+guildServiceName)
	ErrListUserGuildsGuildService    = errcode.NewError(guildServiceBaseCode+6, "failed to ListUserGuilds "+guildServiceName)
	ErrListGuildMembersGuildService  = errcode.NewError(guildServiceBaseCode+7, "failed to ListGuildMembers "+guildServiceName)
	ErrAddGuildMemberGuildService    = errcode.NewError(guildServiceBaseCode+8, "failed to AddGuildMember "+guildServiceName)
	ErrRemoveGuildMemberGuildService = errcode.NewError(guildServiceBaseCode+9, "failed to RemoveGuildMember "+guildServiceName)
	ErrUpdateGuildMemberGuildService = errcode.NewError(guildServiceBaseCode+10, "failed to UpdateGuildMember "+guildServiceName)
	ErrGetGuildMemberGuildService    = errcode.NewError(guildServiceBaseCode+11, "failed to GetGuildMember "+guildServiceName)

	// error codes are globally unique, adding 1 to the previous error code
)
