// Code generated by https://github.com/go-dev-frame/sponge

package ecode

import (
	"github.com/go-dev-frame/sponge/pkg/errcode"
)

// teamService business-level http error codes.
// the teamServiceNO value range is 1~100, if the same error code is used, it will cause panic.
var (
	teamServiceNO       = 92
	teamServiceName     = "teamService"
	teamServiceBaseCode = errcode.HCode(teamServiceNO)

	ErrCreateTeamTeamService     = errcode.NewError(teamServiceBaseCode+1, "failed to CreateTeam "+teamServiceName)
	ErrCloseTeamTeamService      = errcode.NewError(teamServiceBaseCode+2, "failed to CloseTeam "+teamServiceName)
	ErrUpdateTeamTeamService     = errcode.NewError(teamServiceBaseCode+3, "failed to UpdateTeam "+teamServiceName)
	ErrCreateTemplateTeamService = errcode.NewError(teamServiceBaseCode+4, "failed to CreateTemplate "+teamServiceName)
	ErrDeleteTemplateTeamService = errcode.NewError(teamServiceBaseCode+5, "failed to DeleteTemplate "+teamServiceName)
	ErrUpdateTemplateTeamService = errcode.NewError(teamServiceBaseCode+6, "failed to UpdateTemplate "+teamServiceName)
	ErrGetTeamTeamService        = errcode.NewError(teamServiceBaseCode+7, "failed to GetTeam "+teamServiceName)
	ErrListTeamsTeamService      = errcode.NewError(teamServiceBaseCode+8, "failed to ListTeams "+teamServiceName)
	ErrGetTemplateTeamService    = errcode.NewError(teamServiceBaseCode+9, "failed to GetTemplate "+teamServiceName)
	ErrListTemplatesTeamService  = errcode.NewError(teamServiceBaseCode+10, "failed to ListTemplates "+teamServiceName)

	// error codes are globally unique, adding 1 to the previous error code
)
